language: java
sudo: false

jdk:
  - openjdk8

# install:
#   - mvn test-compile -DskipTests=true -Dmaven.javadoc.skip=true -B -V
script:
  - mvn test jacoco:report

# Note:  currently no way to do this once for the entire matrix
#  see https://github.com/travis-ci/travis-ci/issues/929
after_success:
  - mvn coveralls:report

notifications:
  email: false
